name: Quartus Tests

on:
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/quartus.yml"
      - "quartus/**"
      - "src/**"

jobs:
  quartus:
    name: Quartus Tests
    runs-on: ubuntu-latest

    # allow the job to pull from GHCR and read the repo
    permissions:
      contents: read
      packages: read

    # run all steps INSIDE your private Quartus image
    container:
      image: ghcr.io/pedropcventura/rv32i/quartus-18.1:latest
      credentials:
        username: ${{ secrets.GHCR_USER }}   # set this to 'pedropcventura'
        password: ${{ secrets.GHCR_PAT }}    # your PAT with read:packages
      options: -v ${{ github.workspace }}:/var/www

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Show Quartus version
        run: quartus_sh --version

      # ---- build stages (project is 'rv32i') ----
      - name: Run Synthesis (quartus_map)
        run: quartus_map /var/www/quartus/rv32i

      - name: Run Fitter (quartus_fit)
        run: quartus_fit /var/www/quartus/rv32i

      - name: Run Timing Analysis (quartus_sta)
        run: quartus_sta /var/www/quartus/rv32i --do_report_timing --multicorner

      # Collect commonly useful outputs
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: quartus-artifacts
          path: |
            quartus/**/*.sof
            quartus/**/*.pof
            quartus/**/*.rbf
            quartus/**/*.rpt
            quartus/output_files/**
          if-no-files-found: ignore
