# .github/workflows/vhdl_syntax_check.yml
name: VHDL Syntax Check

on:
  push:
    paths:
      - "src/**/*.vhd"
      - "src/**/*.vhdl"
      - "Makefile"
      - ".github/workflows/vhdl_syntax_check.yml"
  pull_request:
    paths:
      - "src/**/*.vhd"
      - "src/**/*.vhdl"
      - "Makefile"

jobs:
  ghdl-check:
    name: GHDL syntax check
    runs-on: ubuntu-latest

    # Run the job inside your GHCR image (has ghdl + yosys)
    container:
      image: ghcr.io/pedropcventura/riscv-dev_tools:yosys-fixed

    # If the repo or image is private, this lets Actions pull from GHCR
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show tool versions
        run: |
          ghdl --version || true
          yosys -V || true

      - name: VHDL syntax check (Makefile target)
        run: make check
